### ISSUE TITLE
caught exception 'data-cid'

### ISSUE THREAD

**Issue by simin75simin** [edsu/etudier#20]
OS:Ubuntu 18.04
python: python3.7.5
chrome version: 91
```
py -m etudier 'https://scholar.google.com/scholar?start=0&hl=en&as_sdt=20000005&sciodt=0,21&cites=17950649785549691519&scipsc='

caught exception 'data-cid'
saving output.html and output.gexf
```
chrome briefly fires up, showing the scholar page for less than a second then the program terminated with the above lines. 

since i used the exact instruction from the readme.md file i don't think an exception should happen. but it did. how do i resolve this? thanks.

**Comment by edsu** [comment]
I think this was fixed in 174e65f3d6d4168ba638e0d80bc20554553924c3 which was released as v0.0.8.
