### ISSUE TITLE
chromedriver, MacOS 'chromedriver cannot be opened because the developer cannot be verified'

### ISSUE THREAD

**Issue by shawngraham** [edsu/etudier#21]
I've installed etudier on a new machine, macos catalina, in a python 3.8 environment. Running etudier, I get the standard Mac pop-up warning 'chromedriver' cannot be opened because the developer cannot be verified'. To get around this, I find this thread on stackoverflow - https://stackoverflow.com/questions/60362018/macos-catalinav-10-15-3-error-chromedriver-cannot-be-opened-because-the-de 

which suggests,

```
xattr -d com.apple.quarantine $(which chromedriver)
```

Even then, still had trouble; had to `brew reinstall chromedriver`, and then did the `xattr` again; after this, etudier ran as expected.

I'm mentioning all this here in case someone else runs into this.

**Comment by edsu** [comment]
Thanks yes, this is tedious but unavoidable I think. I opened the folder containing the chromedriver executable and ctrl-clicked on chromedriver then selected 'open'.
