### ISSUE TITLE
Feature request: Support for search in non-english language

### ISSUE THREAD

**Issue by pjcha** [edsu/etudier#26]
When I tried to do use Etudier to generate map for article on German language of Google search, it only compiled the search from the first page. It will good to at least know in the output that due non-english version of the search it could not complete the search hence failed to generate the map properly.

**Comment by PiyushJadhav** [comment]
Looking at the google scholar links, it contain host language param `hl=en` for English and `hl=de` for German. A simple regex check can be added to change the links to English so that Etudier can also work for non-english links.

**Comment by edsu** [comment]
Where do you see the regex check for `hl`?
