### ISSUE TITLE
Create a citation network based on papers citing one of multiple seed papers? 

### ISSUE THREAD

**Issue by jozilla** [edsu/etudier#30]
I was wondering if it's possible to use etudier to create a citation network based on multiple seed papers, e.g. creating one network from running etudier on multiple Google Scholar "cited by" results pages, one for each seed paper. It looks like this doesn't work by default (multiple Google Scholar URLs can't be provided as arguments).

**Comment by edsu** [comment]
Hmm, you might need to combine the outputs? Which output format are you using?
