### ISSUE TITLE
Write partial results when hitting a Captcha

### ISSUE THREAD

**Issue by volkerkarle** [edsu/etudier#7]
Hi there,
I am receiving so many "I am not a robot" captures that it is impossible for me to end up with any result. I guess there is not way to circumvent this problem?

**Comment by ckudera** [comment]
Can may be solved with: https://github.com/ecthros/uncaptcha2

**Comment by wolfiex** [comment]
No there wouldn't be since it is google which block the ip address temporarily. The only solution I found was to use a VPN when this happens.

**Code improvement suggestion:** There needs to be a redundancy which saves all scraped data at the point of killing the browser (exception handling)

**Comment by 6884** [comment]
THIS. I too was too greedy and called a too big query, and that's what happened. It would REALLY be a great feature to have a temporary dump of whatever had been obtained so far at any point there is a captcha time alert.

**Comment by edsu** [comment]
I like the idea of writing partial results so all is not lost when you get blocked.

**Comment by edsu** [comment]
This is implemented in v0.2.0 that is now available.
