### ISSUE TITLE
[proposed label: enhancement] running headless?

### ISSUE THREAD

**Issue by shawngraham** [edsu/etudier#8]
Hi Ed,

I don't think 'running headless' is exactly the way to express what I had in mind... anyway, I've been building lots of jupyter notebooks served up online with mybinder.org lately. The thought occurred - It'd be very cool if etudier could be run this way (could use in class without losing time to troubleshooting everyone's machines). 

Thing is, binder turns the repo into a container, and then much magic happens; upshot is I can't for the life of me figure out how to bundle up chromedriver, selenium etc to work in that environment. Not that you're not already busy enough... something for the future, maybe.

**Comment by edsu** [comment]
The problem is, you need to complete the Captchas and I don't think you will have access to the browser on Binder?
